name: Publish to PyPi
on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        id: install-build
        run: |
          python -m pip install poetry==1.7.0

      - name: Build
        id: poetry-build
        run: poetry build

      - name: Publish to PyPI
        id: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.8.10
