name: Publish to PyPi
on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install poetry
        id: install-build
        run: |
          python -m pip install poetry==2.1.2

      - name: Build
        id: poetry-build
        run: make build

      - name: Publish to PyPI
        id: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.12.4
